Models/Actor.cs
using System.Xml.Linq;
using IntroToLINQandASPLabs.Data;
namespace IntroToLINQandASPLabs.Models
{
    public class Actor
    {
        private int _id;
        public int Id { get { return _id; } }

        private string _name;
        public string Name
        {
            get { return _name; }
            set
            {
                if (value.Length < 2 || !value.All(c => Char.IsLetter(c) || Char.IsWhiteSpace(c)))
                {
                    throw new Exception("An actors name must be at least 2 letters.");
                }
                else
                {
                    _name = value;
                }
            }
        }

        private int _totalEarned;
        public int TotalEarned { get { return _totalEarned; }  }
        public void GetEarnings()
        {
            int earnings = 0;
            foreach (Role r in _roles) 
            {
                earnings += r.Salary;
            }
            _totalEarned = earnings;
        }

        public int NumOfRoles { get { return _roles.Count; } }

        private HashSet<Role> _roles = new HashSet<Role>();
        public HashSet<Role> Roles { get { return _roles.ToHashSet(); } }

        public void AddRole(Role role)
        {
            _roles.Add(role);
            GetEarnings();
        }

        private HashSet<Rating> _rating = new HashSet<Rating>();
        public HashSet<Rating> Ratings { get { return _rating.ToHashSet(); } }

        public void AddRating(Rating rating)
        {
            _rating.Add(rating);

        }

        public Actor( string name)
        {
            _id = Context.GetNextId();
            Name = name;
            
        }

        public Actor()
        {
            _id = Context.GetNextId();
        }

        
    }
    
}

Controllers/ActorController.cs
using Microsoft.AspNetCore.Mvc;
using IntroToLINQandASPLabs.Data;
using IntroToLINQandASPLabs.Models;

namespace IntroToLINQandASPLabs.Controllers
{
    public class ActorController : Controller
    {
        public IActionResult Index()
        {
            return View(Context.Actors);
        }

        public IActionResult HighestPaidActors()
        {
            HashSet<Actor> orderedActors = Context.Actors.OrderByDescending(a => a.TotalEarned).ToHashSet();
            return View("Index", orderedActors);
        }

        public IActionResult MostRoles()
        {
            HashSet<Actor> orderedActors = Context.Actors.OrderByDescending(a => a.NumOfRoles).ToHashSet();
            return View("Index", orderedActors);
        }

        public IActionResult Details(int actorid)
        {
            try
            {
                Actor actor = Context.Actors.First(a => a.Id == actorid);
                return View(actor);
            } catch (Exception)
            {
                return NotFound();
            }
            
        }
    }
}

Controllers/MovieController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using IntroToLINQandASPLabs.Models;
using IntroToLINQandASPLabs.Data;
using Microsoft.CodeAnalysis;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.View;
using IntroToLINQandASPLabs.Models.ViewModels;

namespace IntroToLINQandASPLabs.Controllers
{
    public class MovieController : Controller
    {
        // GET: MovieController
        public IActionResult Index()
        {

            return View(Context.Movies);
        }



        // GET: MovieController/Details/5
        public IActionResult GetMovieInfo(int movieid)
        {
            if (movieid == 0) { return View(); }

            Movie movie = Context.Movies.FirstOrDefault(m => m.Id == movieid);
            if (movie == null) { return View(); } else
            {
                decimal rating = CalculateOverallRating(movie);
                ViewBag.Rating = rating;
                return View(movie);
            }
        }

        public IActionResult InGenre(string genre)
        {
            List<string> genres = Enum.GetNames(typeof(Context.Genres)).ToList();
            if (genres.Contains(genre, StringComparer.OrdinalIgnoreCase))
            {
                HashSet<Movie> moviesInGenre = Context.Movies.Where(m => m.Genre.ToString().ToLower() == genre.ToLower()).ToHashSet();
                
                    return View("Index", moviesInGenre);

                
            } else
            {
                return RedirectToAction("Error");
            }

            /*
             * 
             * HashSet<Movie> moviesInGenre = Context.Movies.Where(m => m.Genre.ToString().ToLower() == genre.ToLower()).ToHashSet();
             * if (moviesInGenre.Count > 0) {
             * return View("Index", moviesInGenre)
             * } else {
             * return NotFound();
             * }
             */
        }

        public IActionResult GetCountInGenre()
        {
            Dictionary<string,int> CountOfGenre = new Dictionary<string,int>();
            foreach (Movie movie in Context.Movies)
            {
                string genre = movie.Genre.ToString();
                if (CountOfGenre.Keys.Contains(genre))
                {
                    CountOfGenre[genre]++;
                } else
                {
                    CountOfGenre[genre] = 1;
                }
            }


            return View(CountOfGenre);
        }

        public IActionResult MoviesInBudget(int lower, int upper)
        {
            HashSet<Movie> moviesWithinBudget = Context.Movies.Where(m => m.Budget >= lower && m.Budget <= upper).ToHashSet();
            if(moviesWithinBudget.Count > 0)
            {
                return View("Index", moviesWithinBudget);

            } else
            {
                return View("Index", new HashSet<Movie>());
            }

        }

        public IActionResult MoviesInThe90s() 
        {
            HashSet<Movie> In90s = Context.Movies.Where(m => m.ReleaseDate.Year >= 1990 && m.ReleaseDate.Year <= 2000).ToHashSet();
            
            return View("Index", In90s);
        }
       

       public decimal CalculateOverallRating(Movie movie)
        {
            if (movie.Ratings.Any())
            {
                decimal average = movie.Ratings.Average(r => (decimal)r.Score);
                return decimal.Round(average, 2);
            } else
            {
                return 0;
            }

        }

        public IActionResult CompareMovies(string movieIdOne, string movieIdTwo)
        {
            
            // create vm pass to view
            CompareMoviesVM vm = new CompareMoviesVM(Context.Movies, movieIdOne, movieIdTwo);
            
            return View(vm);
        }
        [HttpPost]
        public IActionResult CompareMovies([Bind("MovieIdOne", "MovieIdTwo")]CompareMoviesVM vm)
        {
            // get the Movie Id's from vm and send to Compare in objct

            return RedirectToAction("CompareMovies", new {movieIdOne = vm.MovieIdOne, movieIdTwo = vm.MovieIdTwo});
        }

       

        

        

        
    }
}

Controllers/RatingController.cs
using Microsoft.AspNetCore.Mvc;
using IntroToLINQandASPLabs.Models;
using IntroToLINQandASPLabs.Models.ViewModels;
using IntroToLINQandASPLabs.Data;

namespace IntroToLINQandASPLabs.Controllers
{
    public class RatingController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        

        [HttpGet]
        public IActionResult Create(int id, bool isActor)
        {
            bool boolTest = isActor;
            CreateRatingVM vm;
            try
            {

                if (isActor)
                {
                    Actor actor = Context.Actors.First(a => a.Id == id);
                    vm = new CreateRatingVM(actor);

                }
                else
                {
                    Movie movie = Context.Movies.First(m => m.Id == id);
                    vm = new CreateRatingVM(movie);
                }
            } catch (Exception) { return NotFound(); }

            ViewBag.isActor = isActor;
            ViewBag.id = id;
            return View(vm);
        }

        [HttpPost]
        public IActionResult Create([Bind("Movie", "Actor", "Comment", "Score", "UserId", "Id", "isActor")]CreateRatingVM vm)
        {
            string testOne = vm.Id;
            bool testTwo = vm.isActor;

            //if (vm.Actor== null && vm.Movie == null) { return NotFound(); }
            //if (vm.Actor != null && vm.Movie != null) { return NotFound(); }
            try
            {
                User user = Context.Users.First(u => u.Id == Int32.Parse(vm.UserId));
                int id = Int32.Parse(vm.Id);
                if (vm.isActor)
                {
                    // make actor rating
                    
                    Actor actor = Context.Actors.First(a => a.Id == id );
                    Context.CreateRating(actor, user, vm.Score, vm.Comment);
                    return RedirectToAction("Details", "Actor", new { actorid = id });

                }
                else
                {
                   Movie movie = Context.Movies.First(m => m.Id == id);
                    // make movie rating
                    Context.CreateRating(movie, user, vm.Score, vm.Comment);

                    return RedirectToAction("GetMovieInfo", "Movie", new { movieid = id });
                }

            } catch (Exception)
            {
                return NotFound();
            }
            
            

        }
    }
}

Views/Actor/Details.cshtml
@model IntroToLINQandASPLabs.Models.Actor

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

@if(Model== null)
{
    <h3>Actor not Found</h3>
} else
{
    


<div>
    <h4>Actor</h4>
    <hr />
    <dl class="row">
        
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalEarned)
        </dt>
        <dd class = "col-sm-10">
            <span>$</span>
            @Html.DisplayFor(model => model.TotalEarned)
            <span>Million</span>
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumOfRoles)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumOfRoles)
        </dd>
    </dl>

</div>
<div>
    
        
        @if(Model.Roles.Count > 0)
        {
            <h4>Roles</h4>
            <table class="table">
                <thead>
                    <tr>
                        <th>
                           @Html.DisplayNameFor(model => model.Roles.First().Movie.Title)
                        </th>
                        <th>
                            
                            @Html.DisplayNameFor(model => model.Roles.First().Title)
                        </th>
                        <th>
                            
                            @Html.DisplayNameFor(model => model.Roles.First().Salary)
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach(Role role in Model.Roles)
                    {
                        <tr>
                            <td>
                            <a asp-controller="Movie" asp-action="GetMovieInfo" asp-route-movieid="@role.Movie.Id">@role.Movie.Title</a>
                            </td>
                            <td>
                                @role.Title
                            </td>
                            <td>
                                <span>$</span>@role.Salary <span>Million</span>
                            </td>
                        </tr>
                
                    }
                </tbody>
            </table>
            
        }

</div>
<div>
        @if(Model.Ratings.Count > 0)
        {
            <h4>Ratings</h4>
            <table class="table">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.Ratings.First().User.Name)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Ratings.First().Score)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Ratings.First().Comment)
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach(Rating rating in Model.Ratings)
                    {
                        <tr>
                            <td>
                                @rating.User.Name
                            </td>
                            <td>
                                @rating.Score
                            </td>
                            
                            @if (String.IsNullOrEmpty(rating.Comment))
                            {
                                <td>No Comment</td>
                            } else
                            {
                                <td>
                                    @rating.Comment
                                </td>
                            }
                            
                        </tr>
                    }
                </tbody>
            </table>
            
        }
</div>
}
<div>
    
    <a asp-action="Index">Back to List</a> | 
    @if (Model != null)
    {
        <a asp-controller="Rating" asp-action="Create" asp-route-id="@Model.Id" asp-route-isActor="true">Rate @Model.Name</a>
    }
</div>

Views/Actor/Index.cshtml
@model IEnumerable<IntroToLINQandASPLabs.Models.Actor>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Actors</h1>


<table class="table">
    <thead>
        <tr>
            
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                Num of Roles
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalEarned)
            </th>
            
            
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            
            <td>
               <a asp-action="Details" asp-route-actorid="@item.Id">@item.Name</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumOfRoles)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalEarned)
                <span>M</span>
            </td>
            <td>
                
            </td>

            
            
        </tr>
}
    </tbody>
</table>

<div class="text-center">
    @Html.ActionLink("Highest Paid Actor", "HighestPaidActors")
    @Html.ActionLink("Most Roles", "MostRoles")

</div>