Controllers/ActorController.cs
using Microsoft.AspNetCore.Mvc;
using IntroToLINQandASPLabs.Data;
using IntroToLINQandASPLabs.Models;

namespace IntroToLINQandASPLabs.Controllers
{
    public class ActorController : Controller
    {
        public IActionResult Index()
        {
            return View(Context.Actors);
        }

        public IActionResult HighestPaidActors()
        {
            HashSet<Actor> orderedActors = Context.Actors.OrderByDescending(a => a.TotalEarned).ToHashSet();
            return View("Index", orderedActors);
        }

        public IActionResult MostRoles()
        {
            HashSet<Actor> orderedActors = Context.Actors.OrderByDescending(a => a.NumOfRoles).ToHashSet();
            return View("Index", orderedActors);
        }

        public IActionResult Details(int actorid)
        {
            try
            {
                Actor actor = Context.Actors.First(a => a.Id == actorid);
                return View(actor);
            } catch (Exception)
            {
                return NotFound();
            }
            
        }
    }
}

Controllers/MovieController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using IntroToLINQandASPLabs.Models;
using IntroToLINQandASPLabs.Data;
using Microsoft.CodeAnalysis;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.View;
using IntroToLINQandASPLabs.Models.ViewModels;

namespace IntroToLINQandASPLabs.Controllers
{
    public class MovieController : Controller
    {
        // GET: MovieController
        public IActionResult Index()
        {

            return View(Context.Movies);
        }



        // GET: MovieController/Details/5
        public IActionResult GetMovieInfo(int movieid)
        {
            if (movieid == 0) { return View(); }

            Movie movie = Context.Movies.FirstOrDefault(m => m.Id == movieid);
            if (movie == null) { return View(); } else
            {
                decimal rating = CalculateOverallRating(movie);
                ViewBag.Rating = rating;
                return View(movie);
            }
        }

        public IActionResult InGenre(string genre)
        {
            List<string> genres = Enum.GetNames(typeof(Context.Genres)).ToList();
            if (genres.Contains(genre, StringComparer.OrdinalIgnoreCase))
            {
                HashSet<Movie> moviesInGenre = Context.Movies.Where(m => m.Genre.ToString().ToLower() == genre.ToLower()).ToHashSet();
                
                    return View("Index", moviesInGenre);

                
            } else
            {
                return RedirectToAction("Error");
            }

            /*
             * 
             * HashSet<Movie> moviesInGenre = Context.Movies.Where(m => m.Genre.ToString().ToLower() == genre.ToLower()).ToHashSet();
             * if (moviesInGenre.Count > 0) {
             * return View("Index", moviesInGenre)
             * } else {
             * return NotFound();
             * }
             */
        }

        public IActionResult GetCountInGenre()
        {
            Dictionary<string,int> CountOfGenre = new Dictionary<string,int>();
            foreach (Movie movie in Context.Movies)
            {
                string genre = movie.Genre.ToString();
                if (CountOfGenre.Keys.Contains(genre))
                {
                    CountOfGenre[genre]++;
                } else
                {
                    CountOfGenre[genre] = 1;
                }
            }


            return View(CountOfGenre);
        }

        public IActionResult MoviesInBudget(int lower, int upper)
        {
            HashSet<Movie> moviesWithinBudget = Context.Movies.Where(m => m.Budget >= lower && m.Budget <= upper).ToHashSet();
            if(moviesWithinBudget.Count > 0)
            {
                return View("Index", moviesWithinBudget);

            } else
            {
                return View("Index", new HashSet<Movie>());
            }

        }

        public IActionResult MoviesInThe90s() 
        {
            HashSet<Movie> In90s = Context.Movies.Where(m => m.ReleaseDate.Year >= 1990 && m.ReleaseDate.Year <= 2000).ToHashSet();
            
            return View("Index", In90s);
        }
       

       public decimal CalculateOverallRating(Movie movie)
        {
            if (movie.Ratings.Any())
            {
                decimal average = movie.Ratings.Average(r => (decimal)r.Score);
                return decimal.Round(average, 2);
            } else
            {
                return 0;
            }

        }

        public IActionResult CompareMovies(string movieIdOne, string movieIdTwo)
        {
            
            // create vm pass to view
            CompareMoviesVM vm = new CompareMoviesVM(Context.Movies, movieIdOne, movieIdTwo);
            
            return View(vm);
        }
        [HttpPost]
        public IActionResult CompareMovies([Bind("MovieIdOne", "MovieIdTwo")]CompareMoviesVM vm)
        {
            // get the Movie Id's from vm and send to Compare in objct

            return RedirectToAction("CompareMovies", new {movieIdOne = vm.MovieIdOne, movieIdTwo = vm.MovieIdTwo});
        }

       

        

        

        
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IntroToLINQandASPLabs</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/IntroToLINQandASPLabs.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">IntroToLINQandASPLabs</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="Index">Movies</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Actor" asp-action="Index">Actors</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - IntroToLINQandASPLabs - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_MovieDetail.cshtml
@model IntroToLINQandASPLabs.Models.Movie

<div>
    <h1>@Html.DisplayFor(model => model.Title)</h1>
    <hr />
    <dl class="row">

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ReleaseDateShort)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Genre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Genre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Budget)
        </dt>
        <dd class="col-sm-10">
            <span>$</span>
            @Html.DisplayFor(model => model.Budget)
            <span>M</span>
        </dd>
        <dt class="col-sm-2">
            Rating
        </dt>
        <dd class="col-sm-10">
            @ViewBag.Rating
        </dd>
    </dl>
</div>

@if (Model.Roles.Count > 0)
{

    <h4>Roles</h4>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Roles.First().Actor.Name)
                </th>
                <th>

                    @Html.DisplayNameFor(model => model.Roles.First().Title)
                </th>
                <th>

                    @Html.DisplayNameFor(model => model.Roles.First().Salary)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (Role role in Model.Roles)
            {
                <tr>
                    <td>
                        <a asp-controller="Actor" asp-action="Details" asp-route-actorid="@role.Actor.Id">@role.Actor.Name</a>
                    </td>
                    <td>
                        @role.Title
                    </td>
                    <td>
                        <span>$</span>@role.Salary <span>Million</span>
                    </td>
                </tr>

            }
        </tbody>

    </table>
}
<div>
    @if (Model.Ratings.Count > 0)
    {
        <h4>Ratings</h4>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Ratings.First().User.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Ratings.First().Score)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Ratings.First().Comment)
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (Rating rating in Model.Ratings)
                {
                    <tr>
                        <td>
                            @rating.User.Name
                        </td>
                        <td>
                            @rating.Score
                        </td>

                        @if (String.IsNullOrEmpty(rating.Comment))
                        {
                            <td>No Comment</td>
                        }
                        else
                        {
                            <td>
                                @rating.Comment
                            </td>
                        }

                    </tr>
                }
            </tbody>
        </table>

    }
</div>